Initial topbar with search functionality
acmucsd-projects/wi21-lion pull request #8
Opened 2021-02-14 01:08 UTC by atar13

2021-02-14 01:43 UTC, tristinxie requested changes
There are a few styling guidelines I want you to follow. Also, you should separate a lot of these components into separate files.

2021-02-14 01:43 UTC, tristinxie commented on client/src/homeComponents/topBarComponents/TopBar.js
> +        return courseName.includes(query.toUpperCase())
Have consistent semicolons throughout your code. Every line should have a semicolon.

2021-02-14 01:43 UTC, tristinxie commented on client/src/homeComponents/topBarComponents/TopBar.js
> +    return (<div id="search-results-container" ref={resultsWrapperRef} >
keep return lines consistent in this style:
```
return (

)
```

2021-02-14 01:43 UTC, tristinxie commented on client/src/homeComponents/topBarComponents/TopBar.js
> +                <div className="topbar-buttons" style={{ marginRight: '2vw', paddingRight: '1vh', paddingLeft: '1vh' }}>
Move inline style to external css file

2021-02-14 01:43 UTC, tristinxie commented on client/src/homeComponents/topBarComponents/TopBar.js
> +    const { query} = props
consistent spacing

2021-02-15 20:51 UTC, atar13 commented
I moved each component to its own file. Should I also move each component's style to a seperate css file?

2021-02-16 04:19 UTC, tristinxie reviewed
Looks good so far! Request for approval again once you are satisfied with the functionality.

2021-02-16 23:07 UTC, tristinxie approved these changes

2021-02-16 23:07 UTC, merged